- hosts: droplet
  become: yes
  tasks:
    - name: Pull API Docker image
      docker_image:
        name: steven743/net-core-devsecops
        source: pull

    - name: Run API container
      docker_container:
        name: net-core-devsecops
        image: steven743/net-core-devsecops
        state: started
        restart_policy: always
        ports:
          - "80:5072"
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: pip install ansible

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run Ansible Playbook
      run: |
        ansible-playbook ansible/deploy.yml -i ansible/inventory
