name: DAST - OWASP ZAP Scan

on:
    push:
      branches:
        - main
    pull_request:
      types: [opened, synchronize, reopened]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build and run .NET API
      run: |
        cd NetCoreApis
        docker build -t myapi .
        docker run -d -p 5072:8080 --name myapi-container myapi
        sleep 15 # wait for API to be fully up

    # Run ZAP Baseline Scan using Docker
    - name: Run ZAP Baseline Scan
      continue-on-error: true
      run: |
        docker run \
          --user root \ 
          --network="host" \
          -v ${{ github.workspace }}:/zap/wrk/:rw \
          ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
          -t http://localhost:5072 \
          -g gen.conf \
          -r zap_report.html \
          -x zap_report.xml \
          -J zap_report.json \
          -I

    # Upload HTML report as artifact
    - name: Upload ZAP Report
      uses: actions/upload-artifact@v4.6.2
      with:
        name: ZAP Scan Report
        path: zap_report.html
