name: DAST - OWASP ZAP Scan

on:
    push:
      branches:
        - main
    pull_request:
      types: [opened, synchronize, reopened]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build and run .NET API
      run: |
        cd NetCoreApis
        docker build -t myapi .
        docker run -d -p 5072:8080 --name myapi-container -e ASPNETCORE_ENVIRONMENT=Development myapi
        sleep 15 # wait for API to be fully up

    - name: Run ZAP API Scan
      continue-on-error: true
      run: |
        docker run --user root --network="host" \
          -v ${{ github.workspace }}:/zap/wrk/:rw \
          zaproxy/zap-stable zap-api-scan.py \
          -t http://localhost:5072/swagger/v1/swagger.json \
          -f openapi \
          -r zap-report.html
          -d

    - name: Upload ZAP Report
      uses: actions/upload-artifact@v4.6.2
      with:
        name: ZAP Scan Report
        path: zap_report.html
