name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_READ_WRITE_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
    - name: Build Docker image
      run: |
        cd NetCoreApis
        docker build -t net-core-devsecops:latest .
        docker tag net-core-devsecops:latest ${{ secrets.DOCKER_USERNAME }}/net-core-devsecops:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/net-core-devsecops:latest
    
        - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
  
    - name: Install Ansible
      run: pip install ansible

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run Ansible Playbook
      run: |
        ansible-playbook ansible/deploy.yml -i ansible/inventory