name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_READ_WRITE_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
    - name: Build Docker image
      run: |
        cd NetCoreApis
        docker build -t net-core-devsecops:latest .
        docker tag net-core-devsecops:latest ${{ secrets.DOCKER_USERNAME }}/net-core-devsecops:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/net-core-devsecops:latest