name: SAST - Sonarqube

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.406'

      - name: Install dependencies
        run: dotnet restore

      - name: Build the solution
        run: dotnet build --no-restore

      - name: Run SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@v5
        env:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          sonar-project-key: 'StevenYu0124_NET-Core-DevSecOps'
          sonar-project-name: 'NET-Core-DevSecOps'

      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      - name: Publish results to SonarCloud
        run: dotnet sonarscanner end